<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0;">
<title>LFC Services Home Repair Division</title>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,300,400,600,700,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="css/main.css" />
<link rel="stylesheet" type="text/css" href="css/terms.css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="js/skrollr.js"></script>
<script src="js/waypoints.js"></script>
<script src="js/waypoints-sticky.js"></script>
<script src="js/readyInt.js"></script>
<script src="js/loadTerms.js"></script>
</head>

<body>    

	<?php include 'http://lfchomerepair.com/php/load.php';?>
    
    <?php include 'http://lfchomerepair.com/php/header.php';?>
    
    <div id="terms" class="panel two">
    	<div class="container">
        	<div class="one">
            	<h1>TERMS &amp; CONDITIONS</h1>
            </div>
                <div class="content">
                	<p>General Conditions</p>
                	<ol>
                    	<li>The term "Owner" refers to any and all parties who have ownership of the property. The term "Contractor" refers to LFC Services, Inc.</li>
                    	<li>I (We) the undersigned am (are) the only owner(s) of record of said property.</li>
                    	<li>This Contract constitutes the entire understanding of the parties and no other understanding, collateral, verbal, or otherwise, shall be binding unless in writing and signed by both parties. This Contract is binding upon heirs, executors, administrators, and successors and assigns of the Owner(s), however, the obligations of Contractor pertain to the Owner(s) only and no other party whatsoever and the obligations of the Contractor pursuant to this Contract shall not be assigned to any other party(ies) without the express written permission and approval of Contractor. Any and all costs incurred by Contractor in the collection of payment(s) due under this Contract, including reasonable attorney's fees and applicable interest, shall be reimbursed to the Contractor by the Owner(s).
Any addit
</li>
                    	<li>Any additional work not contemplated within the terms and conditions of this Contract shall be addressed by a written Contract Addendum executed by both parties. Changes may delay completion date and are payable one hundred percent (100%) upon execution.</li>
                    	<li>This Contract is contingent upon the Owner(s) verification that the proposed construction in no way violates any restrictive covenants, and that any violation shall be the Owner(s) sole responsibility.</li>
                    	<li>The Contract and Plans, when applicable, shall be signed in not less than triplicate by the Owner(s) and the Contractor.</li>
                    	<li>This Contract may be withdrawn by the Contractor unless executed by the Owner(s) and Contractor. Owner(s) understand(s) the start/completion dates specified are subject to revision in the event that this agreement is not signed upon presentation.</li>
                    	<li>Contractor shall not be liable for any damages resulting from, or for, any delay or inability to perform due to strikes, fire, acts of God other natural causes (including weather), acts of public authorities or enemies, or any other cause(s) beyond the control of the Contractor.</li>
                    	<li>Survey, BZA approval, Historic Commission Approval or occupancy permit, if required, are to be by the Owner(s). Other permits necessary for the execution of the work shall be applied for by the Contractor. This Contract is subject to issuance of such permits and other required approvals by local building inspectors based on the Contract plans and/or Contract.</li>
                    	<li>Contractor shall obtain and pay for permits, as noted, for the execution of the work. This Contract is subject to issuance of such permits and other required approvals by local building inspectors based on the Contract. We assume no work will be required due to existing code violations. Survey and/or variance, if required, will be provided and paid for by the Owner(s). Furthermore, if during the permit process, existing zoning or code violations require additional plans and/or plan alterations, they will be additional, and billed at $90.00 per hour.</li>
                    	<li>Asbestos, radon gas, mold and/or lead removal/disposal and/or encapsulation have not been included or anticipated unless specifically stated. The United States Environmental Protection Agency (EPA) and some local departments of health have expressed concern over the presence of asbestos, radon gas, mold and/or lead in the home. Prolonged exposure to high levels of asbestos, radon gas, mold, its progeny and/or lead may affect the health of residents. Contractor has made no investigation to determine whether there is asbestos, radon gas, mold, lead and/or any other environmental pollutants or health hazards in the home, or affecting the premises. Contractor disclaims any representation or warranty as to the presence or lack of asbestos, radon, mold, lead, and/or any hazardous environmental or health condition, or as to the effect of asbestos, radon, mold, lead, and/or any such condition on the premises or residence, before or after completion of all work done pursuant to this Contract. Without waiving this disclaimer, however, for housing built prior to 1978 and other applicable premises, Contractor shall perform its work in accordance with the requirements of the Environmental Protection Agency's lead-based paint renovation regulations generally located at 40 C.F.R. (Code of Federal Regulations) Part 745, Subpart E. Further, upon the signing of this agreement, the Owner(s) will be given a copy of the pamphlet, "Renovate Right-Important Lead Hazard Information for Families, Child Care Providers and Schools", informing them of the potential risk of lead hazard exposure from renovation activity to be performed in their home. Owner(s) to receive this pamphlet before the work begins.</li>
                    	<li>If a parking ban is in effect in Owner's area, Owner(s) is (are) to provide permits for workmen. If permits are not provided, Owner(s) will be charged for parking tickets, if any. Owner(s) shall grant free access to work areas for Contractor and agrees to keep driveway clear and available for movement of materials and vehicles.</li>
                    	<li>Owner(s) shall provide a bathroom facility for the workers. Owner(s) shall provide a key to be placed in a lock box (provided by Contractor) on the premises during construction. Owner(s) understand Contractor will display a job sign during construction.</li>
                    	<li>The Owner(s) agree(s) that, should access to neighboring property be required for the performance of the work as outlined herein, the Owner(s) will secure written permission from any neighbors affected in advance of commencement of said work.
</li>
                    	<li>The Owner(s) agree(s) that no subcontractors, or other workmen, hired by him/her shall work on the job site for the duration of this Contract, unless agreed to by the Contractor, in writing.</li>
                    	<li>The Owner® understand(s) that before and after photographs of the areas to be remodeled may be taken by Contractor for its sole use. Should any other use be desired, it is agreed that the photos will not be used without prior consent of the Owner(s).
</li>
                    	<li>Owner® understand(s) that it is his/her responsibility to review his/her homeowner's insurance policy in relation to this Contract. Materials and/or equipment become the responsibility of the Owner(s) once installed on the premises.</li>
                    	<li>Contractor shall not be held liable for non-negligent damage to driveway, lawns, shrubs and vegetation caused by normal movement and storage of labor and materials.</li>
                    	<li>Unless stated otherwise, excavated soil to be spread on-site. No seed, sod, shrub/tree removal/relocation or fine grading has been included in this Contract. Excavation for footings/piers, if any, is limited in depth to the established local frost line and does not contemplate filled ground, or ground of inadequate bearing capacity, or rock or any other material not removable by ordinary hand tools. Extra work, if required, will be charged on a time and material basis.</li>
                    	<li>The Contractor is to provide dust protection as practical. Owner(s) agree to remove and protect all personal property from area(s) to be affected prior to commencement. Movement/protection of personal belongings by Contractor personnel, if required, shall be charged on a time basis. Care will be taken, but Contractor will not be responsible for damage or loss, if any.</li>
                    	<li>Contractor reasonably assumes the existing structure scheduled to remain is in good condition and will not require work except as specifically noted. Structural work or repairs, if required and specified, will be limited to replacing or reinforcing the existing structure using standard building practices. Structural engineering has not been anticipated and/or included unless specifically stated.</li>
                    	<li>In executing this Contract, it is reasonably assumed by Contractor, that the walls/ceilings to be removed, if any, conceal no pipes, electrical feeder lines or ducts. Furthermore, rerouting, relocation or replacement of vents, pipes or, ducts or conduits that may be encountered in areas of alteration or excavation has not been included, except as noted. If there are walls to be removed or altered, it is reasonably assumed that they are non-bearing, and reasonably assumed that the existing floors, walls, ceilings and roofs, are to be level, plumb, and are to conceal no structural damage/problems, pipes, electrical feeder lines or ducts. Work, if required, for re-engineering, re-framing, re-routing, relocation or replacement of existing studs, joists, rafters, beams, posts, wires, vents, pipes, ducts, or conduits that may be encountered in the areas of alteration or excavation has not been included, except as noted, and will be quoted upon discovery in an addendum. If specified, repairs for any rotted or decayed materials are limited to visually apparent conditions. If concealed damage is encountered, Contractor will present an addendum to repair the additional work.</li>
                    	<li>Unless otherwise specified, any changes to upgrade the existing electric service and/or panel, to make adequate for additional wiring is not included in this Contract. Existing switches and duplex outlet devices, which are not scheduled for relocation/reworking, are to remain. New switches and devices are to be white, unless otherwise specified. Recessed light locations are subject to joist location and/or existing conditions. Security, antenna or fire system relocation, as well as utility company charges, if required, are to be arranged and paid for by the Owner(s).</li>
                    	<li>Unless otherwise specified, any changes to upgrade the existing plumbing, systems and/or service to make adequate for additional fixtures, and any changes to upgrade the existing heating and air conditioning systems is not included in this Contract. Existing fixtures, pipes, drains, septic systems, wells, vents, and equipment that are not scheduled for relocation or reworking are to remain. Utility company charges, if any, are to be paid for by Owner(s).
</li>
                    	<li>Materials are to be as specified. Contractor reasonably assumes that all un-specified materials are available as stock items. If a specified material is not available Contractor will consult with the owner&reg; and present a written contract addendum for their approval. Custom run items are not anticipated or included in this Contract unless specifically specified. Contractor reasonably assumes that any Owner provided items shall be on site and in working condition prior to the start of work. Additional costs to reschedule, rework or reinstall owner provided items shall be billed to the Owner(s) at T&amp;M rates. Trim carpentry to be stock, one-piece, and finger-jointed, unless otherwise specified (note: finger-jointed material does not lend itself to stain).</li>
                    	<li>Areas disturbed by construction will be patched to blend with the existing areas as reasonably practical. Furthermore, paint or paint touch up that may be required following attendant damage repair on call back items during the warranty period is expressly not included herein and shall be the sole responsibility of the Owner(s).</li>
                    	<li>Unless otherwise specified, painting is not included in this Contract. Normal paint preparation (i.e., caulking and filling nail holes) is also to be performed by others, except exterior caulking at doors and windows. Owner(s) is to call to Contractor's attention to any drywall or plaster defects prior to the final coat of paint or wallpaper. Further, paint/paint touch-up that may be required following attendant damage repair or call back items during the warranty period is not included and is the sole responsibility of the Owner(s).</li>
                    	<li>Contractor is to haul all construction debris caused by construction, and upon completion, will leave job in a broom clean condition. All material removed in the course of alterations shall be disposed of by Contractor except those items designated by Owner(s) in writing prior to commencement of construction.</li>
                    	<li>Unless specifically noted, the Contractor shall pay all sales, consumer use and other similar taxes required by law.</li>
                    	<li>The Definition of allowance as used in this Contract: An allowance is a specified sum of money set aside for an item about which there is not enough information to establish an accurate price. The specified sum is an educated guess and the actual cost may vary. Once an actual cost is established, owner(s) will be charged/credited any difference through a Contract addendum. Allowances as noted, are at Contractor cost plus thirty-three percent (33%).</li>
                    	<li>If "Time and Materials" work is specified in this Contract, shown on the plans or approved in an addendum, it shall be charged at $65.00 per hour for a carpenter/mechanic, $25.00 per hour for a helper, $90.00 per hour for supervision/design, $45.00 per hour for truck. Materials and allowances are at Contractor's cost plus thirty-three percent (33%). Upon completion of the work, the actual costs will be compiled and billed to the Owner(s) through a Contract addendum.</li>
                    	<li>Any controversy or claim arising out of or relating to this Contract in any manner whatsoever, or breach thereof, shall be settled by final and binding arbitration before a single Arbitrator in the Washington, D.C. metropolitan area in accordance with the Construction Industry Arbitration Rules of the American Arbitration Association (fee schedule attached), currently in effect, and judgment upon the award rendered by the Arbitrator may be entered in any Court having jurisdiction thereof. [For Maryland homeowners any claim by him/her v. the Home Improvement Guaranty Fund shall be stayed until completion of any such arbitration proceeding per section 8-405(c) of Bus. Reg. Art. of MD Ann. Code.]</li>
                    	<li>As a condition precedent, however, to the filing of any demand for Arbitration or legal action pursuant to Paragraph 32 above, the parties shall endeavor to resolve their Claims by mediation, which, unless the parties mutually agree otherwise, shall be in accordance with the Rules of Mediation currently in effect of the Better Business Bureau serving the area where the work is located. The parties shall share any Mediator's fee and any filing and/or administration fees equally. The mediation shall be conducted at the offices of the Better Business Bureau serving the area where the work is located, unless another location is mutually agreed upon. Any settlement reached in mediation shall be enforceable as a settlement agreement in any court having jurisdiction thereof.
</li>
                    	<li>Contractor warrants that all work self-performed by it and performed by its subcontractors pursuant to the Contract shall be of workmanlike quality and shall be in accordance with all applicable building codes and the NAHB Residential Construction Performance Guidelines. Provided the Owner® is in full compliance with the terms and conditions in the Contract, including all payment provisions therein, the Contractor shall remedy any defect in workmanship that is not the result of normal wear that appears within a period of five (5) years from the date of substantial completion for work self-performed by it and' shall remedy any defect in workmanship that is not the result of normal wear that appears within a period of two (2) years from the date of substantial completion for work performed by its subcontractors. In no event, however, does this warranty extend beyond five (5) years for self-performed work from the date of substantial completion and two (2) years for subcontracted work from the date of substantial completion. If materials and equipment furnished pursuant to the Contract are warranted by any manufacturer, such manufacturer's warranty is the Owner's sole and exclusive warranty. The Contractor is not responsible for determining if any such warranties exist. Contractor cannot warrant Owner supplied materials. The Contractor reserves the right to conduct an annual inspection of the work at a time mutually convenient to both the Contractor and the Owner(s). The above warranty excludes and is in lieu of any other warranty express, implied or otherwise. This warranty is for the Owner's benefit only, and to no other party whatsoever.	•</li>
                    	<li>Contractor cannot warrant any work done to repair any type of leak including, roofs, chimneys, gutters & downspouts, skylights, doors, windows, plumbing fixtures, showers, tubs, foundations, and basements. Upon owner's request, the Contractor will make a reasonable attempt to find and resolve the cause of the leak solely on a TWA basis. However, Contractor shall not be held liable in any manner whatsoever if the attempt(s) fail to correct the problem. Contractor cannot warranty any painting work unless proper preparation work including replacement of old surfaces, if required, is specifically noted in this Contract. Application of a new coat(s) of paint over existing surfaces, without full preparation, shall not be covered under this warranty.</li>
                    	<li>BUYER'S RIGHT TO CANCEL — You, the Owner(s), may cancel this transaction at any time prior to midnight of the third business day after the date of this transaction. Sec the attached notice of cancellation form for an explanation of this right.</li>
                    </ol>
                    <p class="sixteen">MARYLAND: All home improvement Contractors and subcontractors must be licensed by the Home Improvement Commission. 
Inquiries about a Contractor should be transmitted to the Home Improvement Commission, telephone (410) 659-6309.</p>
            </div>
        </div>
    </div>
    
    <?php include 'http://lfchomerepair.com/php/footer.php';?>
  
</body>
</html>